config/routes.rb
Todolist::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :tasks, only: [:index, :show, :create, :destroy, :update, :edit] do
    collection do
      get 'completed'
    end
    member do
      post 'complete'
      post 'reopen'
      post 'reposition'
    end
    resources :activities, only: [:index]
  end
  
  resources :activities, only: [:index]
  
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :tasks, except: [:new, :edit] do
        resources :activities, only: [:index]
      end
      resources :activities, only: [:index]
      resources :me, only: [:index]
    end
  end
  
  root 'tasks#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :title, presence: true
  validates_inclusion_of :completed, :in => [ true, false ]
  
  scope :todo, -> { where(completed: false).order(:position) }
  scope :completed, -> { where(completed: true).order(completed_at: :desc) }
  
  def self.limited_completed(limit)
    completed.limit(limit)
  end
  
  def self.completed_count
    completed.count
  end
  
  include ReadableUrl
end

app/controllers/api/v1/tasks_controller.rb
module Api
  module V1
    # Only implement the happy path.
    # If the happy path fails, it should raise an exception.
    # Exceptions are caught and handled by the Api::ApiController.
    class TasksController < Api::ApiController
      interactor_namespace :task
      
      def index
        @tasks = TaskListViewModel.new
        fresh_when last_modified: Task.maximum(:updated_at)
      end
      
      def show
        @task = Task.find(params_id)
        fresh_when @task
      end
      
      def create
        @task = find_business_method(params[:task]) do |method, params|
          method.for(:title) { ac(:create_task, params[:title]) }
        end
        render "show", status: :created, location: api_v1_task_url(@task)
      end
      
      def update
        # Example of different sets of attributes resulting in different business actions
        # method.for(attr-list) tests whether all of the given attributes are part of the request
        # and no additional attributes are provided.
        # If none of the method.for-blocks runs, an exception will be raised indicating the
        # request was invalid.
        @task = find_business_method(params[:task]) do |method, params|
          method.for(:title) { ac(:update_task, params_id, params[:title]) }
          method.for(:position) { ac(:update_task_position, params_id, params[:position]) }
          method.for(:completed) { params[:completed] ? ac(:complete_task, params_id) : ac(:reopen_task, params_id) }
        end
        render "show"
      end
      
      def destroy
        ac(:delete_task, params_id)
        render nothing: true, status: :no_content
      end
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  interactor_namespace :task

  def index
    @task_list = e TaskListViewModel.new
  end
  
  def completed
    @completed = e Task.completed
  end
  
  def create
    @task = bc :create_task, title
    render "create"
  rescue ActiveRecord::RecordInvalid => exception
    @errors = exception.record.errors
    render template: "tasks/error"
  end
  
  def destroy
    @task = bc :delete_task, params_id
  end
  
  def edit
    @task = e Task.find(params_id)
    TaskPolicies::ModifyableTaskPolicy.new(@task).enforce
  end
  
  def update
    @task = bc :update_task, params_id, title
    render "show"
  rescue ActiveRecord::RecordInvalid => exception
    @task = e exception.record
    render "edit"
  end
  
  def show
    @task = e Task.find(params_id)
  end
  
  def reposition
    @task = bc :update_task_position, params_id, position
    render "show"
  end
  
  def complete
    @task = bc :complete_task, params_id
  end
  
  def reopen
    @task = bc :reopen_task, params_id
  end
  
  private
    def title
      params[:task][:title]
    end

    def position
      params[:task][:position].to_i
    end

    # Global catch for all controller methods
    # Works if app has some centralized response to errors
    rescue_from ActiveRecord::RecordNotFound do |exception|
      error = exception.message
      render  js: "alert(\"#{error}\"); window.location.reload();"
    end

    # Handle business method problems. The cause is often concurrency
    rescue_from ArgumentError do |exception|
      error = exception.message
      render js: "alert(\"#{error}\"); window.location.reload();"
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_complete_task.html.erb
<%= named_list(task.id) do %>
	<%= task.checkbox_for_task self, reopen_task_path(task) %>
	<span class="date">(<%= task.completed_at_for_user %>)</span>
	<%= task.label_for self %>
	<%= link_to_remove task %>
	<%= task.link_to_activities self, task %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for task, remote: true do |f| %>
	<% task.errors.full_messages.each do |msg| %>
		<div class="error_msg"><%= msg %></div>
	<% end %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<div class="spinner"></div>
	<br>
	<%= f.submit data: { disable_with: 'Saving...' } %>
	<%= task.cancel(self) %>
<% end %>

app/views/tasks/_incomplete_task.html.erb
<%= named_list(task.id) do %>
	<%= content_tag 'span', 'Move', class: 'handle', data: { url: reposition_task_path(task) } %>
	<%= task.checkbox_for_task self, complete_task_path(task) %>
	<%= task.label_for self %>
	<%= link_to 'Edit', edit_task_path(task), remote: true %>
	<%= link_to_remove task %>
	<%= task.link_to_activities self, task %>
<% end %>

app/views/tasks/_task_list.html.erb
<div id="ajax-error"></div>

<h2>To do</h2>
<% cache Task.maximum(:updated_at) do %>
	<ul id="incomplete-tasks" class="sortable">
		<%= task_list.todo.render(self) %>
	</ul>

	<a href="#" id="add-task">Add task</a>
	<div id="add-task-form" style="display:none">
		<%= render "form", task: task_list.blank_task %>
	</div>

	<h2>Completed</h2>
	<ul id="complete-tasks">
		<%= task_list.limited_completed.render(self) %>
		<%= task_list.show_more(self) %>
	</ul>

<% end %>

app/views/tasks/complete.js.erb
list.removeTask('<%= @task.id %>')
list.completeTask('<%= j @task.render(self) %>')

app/views/tasks/completed.js.erb
<% cache Task.maximum(:updated_at) do %>
	$("#show-more").remove();
	$("#complete-tasks").html("<%= j render partial: "complete_task", collection: @completed, as: 'task' %>");
<% end %>

app/views/tasks/create.js.erb
list.addTask('<%= j @task.render(self) %>')
list.prepareFormForNextEntry()

app/views/tasks/destroy.js.erb
list.removeTask('<%= @task.id %>')

app/views/tasks/edit.js.erb
list.replaceHtml("<%= @task.id %>", "<%= j render("form", task: @task) %>")
list.focusOnText(<%= @task.id %>)

app/views/tasks/error.js.erb
<% @errors.full_messages.each do |msg| %>
	alert("<%= raw msg %>");
<% end %>
location.reload();

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<%= link_to 'Activities', activities_path %>

<%= @task_list.render(self) %>

app/views/tasks/reopen.js.erb
list.removeTask('<%= @task.id %>')
list.addTask('<%= j @task.render(self) %>')

app/views/tasks/show.js.erb
list.replaceRow("<%= @task.id %>", "<%= j render("incomplete_task", task: @task) %>")
list.highlightTask(<%= @task.id %>)

app/views/tasks/update.js.erb
list.highlightUpdatedPosition(<%= @task.position %>)